### ISSUE TITLE
Reorganize schema to support sub-regional codes and to differentiate owner location and coverage

### ISSUE THREAD

**Issue by ivbeg** [commondataio/dataportals-registry#21]
**Current situation**

Country name and country id are part of _country_ attribute; it's mostly related to the owner of the data catalog but sometimes could be related to coverage of the data catalog. For example, https://gws-access.jasmin.ac.uk/public/odanceo/S2_L2/collection.json STAC server owner located in the UK, but it covers Ghana territory.

Another question is that some countries are big and search engine users could be interested in local datasets. So sub-regional/regional level needs to be added to the data catalog description.

**Solution**
1. Create _owner_ attribute with name, link, and  type sub-attributes and add _location_ attribute
2. _location_ attribute could include: country_id, country_name, subregion_id, subregion_name
3. Create _coverage_ attribute as an array of the location attributes
4. Consider optional attribute _address_ under _location_ attribute
5. Convert automatically current _countries_ attribute to coverage and owner attributes. If countries include more than one record, use first for owner location and all of them for coverage

**Example**

Result should look like

```yaml
access_mode:
- public
api: true
api_status: uncertain
catalog_type: Geoportal
content_types:
- dataset
- map_layer
description: Sentinel 2 Surface Reflectance over Ghana using SIAC AC.
endpoints:
- type: stacserverapi
  url: https://gws-access.jasmin.ac.uk/public/odanceo/S2_L2/collection.json
export_standard: STAC specification
id: s2-for-ghana
langs:
- EN
link: https://gws-access.jasmin.ac.uk/public/odanceo/S2_L2/collection.json
name: S2 for Ghana
owner:
- name: "Jasmin. The UK's data analysis facility for environmental science"
- link: "https://jasmin.ac.uk"
- type: Academy
- location:
   - level: 2
   - country:
       - id: UK
         name: United Kingdom
   - subregion
       - id: GB-ENG
       - name: England
coverage:
   - location: 
      - country: 
         - id: GH
         - name: Chana
      - level: 1
software: Stac-server
status: active
tags:
- geospatial
- has_api
```
